### ISSUE TITLE
Remove the managed SCIP layer

### ISSUE THREAD

**Issue by matbesancon** [scipopt/SCIP.jl#184]
In the recent rewrite of https://github.com/jump-dev/HiGHS.jl, @odow removed the managed layer which I had written mimicking the SCIP one, using a pointer to the solver instance directly in the Optimizer struct.

I wonder if we should do the same in SCIP -> implement the logic in managed SCIP at the Optimizer level? We have more going on at this level than there was in HiGHS

**Comment by rschwarz** [comment]
I have no problem with this kind of change. I don't believe anyone is using SCIP.jl without going through MOI.

The initial motivation was to keep the MOI layer light, I guess, but the complexity is just moved, not removed.
Dropping the intermediate layer would also simplify the overall code, because there are currently two separate types of variable and constraint indices.

**Comment by matbesancon** [comment]
perfect, I'll try to work on it
